# Generated by Django 2.1.7 on 2019-04-18 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='小程序名字')),
                ('appid', models.CharField(max_length=200, verbose_name='微信小程序appid')),
                ('secret', models.CharField(max_length=300, verbose_name='微信小程序appsecret')),
                ('login_duration', models.SmallIntegerField(default=30, verbose_name='登录过期时间(天)')),
                ('session_duration', models.PositiveIntegerField(default=2592000, verbose_name='会话过期时间(秒)')),
            ],
        ),
        migrations.CreateModel(
            name='SessionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=100, verbose_name='会话 uuid')),
                ('skey', models.CharField(max_length=100, verbose_name='会话 Skey')),
                ('create_time', models.DateTimeField(verbose_name='会话创建时间')),
                ('last_vist_time', models.DateTimeField(verbose_name='最近访问时间')),
                ('open_id', models.CharField(max_length=100, verbose_name='openid')),
                ('session_key', models.CharField(max_length=100, verbose_name='session_key')),
                ('user_info', models.CharField(max_length=2048, null=True, verbose_name='已解密的用户数据')),
            ],
        ),
    ]
